# Generated by Django 5.2.4 on 2025-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='arguments',
            field=models.JSONField(blank=True, default=dict, help_text='Arguments used when running the command'),
        ),
    ]