# Generated by Django 5.2.4 on 2025-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jobs', '0003_extend_cron_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandschedule',
            name='arguments',
            field=models.JSONField(blank=True, default=dict, help_text='JSON dictionary of arguments. Use "_positional": ["arg1", "arg2"] for positional args'),
        ),
        migrations.AlterField(
            model_name='commandschedule',
            name='command_name',
            field=models.CharField(choices=[('changepassword', 'changepassword'), ('check', 'check'), ('cleanup_old_data', 'cleanup_old_data'), ('clearsessions', 'clearsessions'), ('collectstatic', 'collectstatic'), ('compilemessages', 'compilemessages'), ('createcachetable', 'createcachetable'), ('createsuperuser', 'createsuperuser'), ('dbshell', 'dbshell'), ('delete_logs', 'delete_logs'), ('diffsettings', 'diffsettings'), ('dumpdata', 'dumpdata'), ('findstatic', 'findstatic'), ('flush', 'flush'), ('generate_report', 'generate_report'), ('hello_world', 'hello_world'), ('inspectdb', 'inspectdb'), ('loaddata', 'loaddata'), ('makemessages', 'makemessages'), ('makemigrations', 'makemigrations'), ('migrate', 'migrate'), ('optimizemigration', 'optimizemigration'), ('remove_stale_contenttypes', 'remove_stale_contenttypes'), ('run_jobs', 'run_jobs'), ('runserver', 'runserver'), ('sendtestemail', 'sendtestemail'), ('shell', 'shell'), ('showmigrations', 'showmigrations'), ('sqlflush', 'sqlflush'), ('sqlmigrate', 'sqlmigrate'), ('sqlsequencereset', 'sqlsequencereset'), ('squashmigrations', 'squashmigrations'), ('startapp', 'startapp'), ('startproject', 'startproject'), ('sync_jobs', 'sync_jobs'), ('test', 'test'), ('testserver', 'testserver')], max_length=255, unique=True),
        ),
    ]
